export const genres: string[] = [
  "Fantasy",
  "Romance",
  "Sci-Fi",
  "Dystopia",
  "Mystery",
  "Thriller",
  "Young Adult",
  "New Adult",
  "Graphic Novel",
  "Manga/Comics",
  "Historical Fiction",
  "Action/Adventure",
  "Children's book",
  "Horror",
  "Contemporary Fiction",
  "Other",
];

// {
//     fiction: [
//       "Fantasy",
//       "Romance",
//       "Sci-Fi",
//       "Dystopia",
//       "Mystery",
//       "Thriller",
//       "Young Adult",
//       "New Adult",
//       "Graphic Novel",
//       "Manga/Comics",
//       "Historical Fiction",
//       "Action/Adventure",
//       "Children's book",
//       "Horror",
//       "Contemporary Fiction",
//       "Other",
//     ],
//     nonFiction: [
//       "Self Help",
//       "Memoir/Biography",
//       "Food/Drink",
//       "Art/Photography",
//       "History",
//       "Travel",
//       "True Crime",
//       "DIY/Crafts",
//       "Education/Learning",
//       "Home/Garden",
//       "Religion/Sprituality",
//       "Health/Wellness",
//       "Science/Technology",
//       "Business/Economy",
//       "Humor/Entertainment",
//       "Other",
//     ],
//   };
