export const tropes: string[] = [
  "Slow burn",
  "Ennemies to lovers",
  "He fell first",
  "Found family",
  "Morally gray MMC",
  "Forced proximity",
  "Arranged mariage",
  "Vampires",
  "Werewolves",
  "Witches",
  "Magic",
  "Fae",
  "Pirates",
];
